### ISSUE TITLE
Laravel 9

### ISSUE THREAD

**Issue by carlituxman** [mondago/laravel-azure-application-insights#7]
- mondago/laravel-application-insights[0.5.0, ..., 0.5.1] require laravel/framework ^8.0 -> found laravel/framework[v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.19).

**Comment by ingalless** [comment]
Hey @carlituxman

Thanks for opening the issue.
We've just released a new version with support for Laravel 9 (v0.6.0).

We've also added a support matrix to the readme to better document which laravel version are supported by which versions of this package.
